### ISSUE TITLE
Spring Fling Schedule Update

### ISSUE THREAD

**Issue by powersa** [cugos/cugos.github.com#105]
Update the event page to reflect the proposed schedule, which combines talks in the morning with tutorial/hack/project tracks in the afternoon. We'll discuss this at the 4/15 meeting and get feedback from the larger group.

### TODO

- [x] Add track descriptions or relevant placeholders
- [x] Update the schedule with the time blocks up for discussion
- [x] add sponsors
- [x] update schedule with "shared time tracks"

**Comment by powersa** [comment]
Rough schedule outline:

9:00 through 10:15 -- long form talks (20 minutes apiece)
10:15 through 11:00 -- lightning talks (5 minutes apiece)
11:00 through 12:00 -- intro to projects, break into groups, get up to speed
12:00 through 13:00 -- lunch break + time to catch up in the groups
13:00 through 14:00 -- second half of the project tutorial session
14:00 through 17:00 -- hack time to work on discrete projects

**Comment by svmatthews** [comment]
![screen shot 2015-04-22 at 9 33 27 pm](https://cloud.githubusercontent.com/assets/1943001/7290629/4756b136-e937-11e4-891b-e7663a41e992.png)

**Comment by svmatthews** [comment]
![screen shot 2015-04-22 at 10 03 25 pm](https://cloud.githubusercontent.com/assets/1943001/7290882/7bee5d3c-e93b-11e4-9fd1-897985bc144f.png)

**Comment by svmatthews** [comment]
Those tracks are put together pretty poorly, IMO. Right now they have a `height` set to them to make sure they line up properly. Not a big deal, but if descriptions are edited you'll want to update the height to fit the maximum length track description accordingly. Height is defined only on larger screen sizes in [this code snippet](https://github.com/cugos/cugos.github.com/commit/af129f1f9a00fbdbacc5c6a18fbe29142902b628#diff-434103b9e5e517640a42aa91fc267675R691).

**Comment by powersa** [comment]
@svmatthews that looks great! As soon as we have the final word on Track 2, we release this to the wild.

**Comment by keum** [comment]
@powersa is there sign up for lightening talk? also were you able confirm talk from Dave Sheen?

**Comment by powersa** [comment]
@keum dragging my :footprints: on getting people signed up for talks. Would love to hear from Dave though, maybe do some brainstorming tomorrow on IRC?

**Comment by keum** [comment]
@powersa yeah totally, will do it on irc tomorrow.

**Comment by svmatthews** [comment]
@powersa here is an updated schedule layout!

![cugos-flingscheduleupdate](https://cloud.githubusercontent.com/assets/1943001/7438848/5ecd6fcc-f020-11e4-8be0-73e6d30fd553.gif)

**Comment by powersa** [comment]
That looks really clean @svmatthews . And pretty much exactly what we need. Watch the organizer sheet for updates as they come in. Description length may be something we need to address.

**Comment by foundatron** [comment]
Nice!

**Comment by svmatthews** [comment]
Hm, the description length might make things a bit more complicated - assuming they are very different in length. I wonder if we can take a couple sentences from each, then build a popup for more information?

**Comment by powersa** [comment]
@foundatron you gonna be at the fling?

**Comment by foundatron** [comment]
Yeah!

**Comment by powersa** [comment]
@svmatthews check it :arrow_up:

**Comment by svmatthews** [comment]
[5-10 minutes talks that electrify](https://www.youtube.com/watch?v=JFMtBibwrgY)

**Comment by powersa** [comment]
and we found the event theme song

**Comment by svmatthews** [comment]
SHUT IT DOWN!
